#!/usr/bin/env bash
# configure new Ubuntu machine
sudo apt-get update -y
sudo apt-get install nginx -y
PATH="/etc/nginx/sites-available/default"
sudo sed -i "/server {/a\ \tadd_header X-Served-By '$HOSTNAME';" $PATH
sudo service nginx restart
