#!/usr/bin/env bash
echo $$ > /var/run/myscript.pid
trap 'echo "Y U no love me?!"' INT
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' TERM
while true; do echo "To infinity and beyond"; sleep 2; done
